### ISSUE TITLE
Grievance 

### ISSUE THREAD

**Issue by x0reaxeaxsbiggestfan** [x0reaxeax/rwlazer-alpha#1]
Hi, I'd like to file a grievance. Your tool directly influences my cousin's sister's nephew. He says he can code it better than you. I'd like to discuss this in person. We can work something out. You can pay us to take your source code and improve it. Thx. xoxo

**Comment by x0reaxeax** [comment]
Hi, you forgot to post your Windows version from `winver` command, closing this..

**Comment by x0reaxeaxsbiggestfan** [comment]
bullshit

**Comment by x0reaxeaxsbiggestfan** [comment]
refund

**Comment by x0reaxeax** [comment]
Sir, this is Wendy's
